### YamlMime:YamlDocument
documentType: LandingData
title: Azure Container Service 與 Kubernetes 文件
metadata:
  document_id: null
  title: Azure Container Service 與 Kubernetes 文件 - 教學課程、API 參考 | Microsoft Docs
  meta.description: 'Azure Container Service allows you to quickly deploy a production ready Kubernetes cluster. Learn how to use Azure Container Service in concert with Kubernetes with these quickstarts, tutorials, and samples.'
  services: container-service
  author: carolz
  manager: carolz
  ms.service: container-service
  ms.tgt_pltfrm: na
  ms.devlang: na
  ms.topic: landing-page
  ms.date: 07-21-2017
  ms.author: carolz
abstract:
  description: Azure Container Service 可讓您快速部署可進行生產的 Kubernetes 叢集。 了解如何透過快速入門、教學課程和範例來使用 Azure Container Service 搭配 Kubernetes。
sections:
  - title: 5 分鐘快速入門
    items:
      - type: paragraph
        text: 了解如何使用 Azure Container Service 部署 Kubernetes 叢集：
      - type: list
        style: icon48
        items:
          - image:
              src: 'https://docs.microsoft.com/media/logos/logo_linux.svg'
            text: Linux
            href: /azure/container-service/kubernetes/container-service-kubernetes-walkthrough
  - title: 逐步教學課程
    items:
      - type: paragraph
        text: 了解如何部署、管理及更新 Azure Container Service Kubernetes 叢集中的應用程式。
      - type: list
        style: ordered
        items:
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-prepare-app">從應用程式建立容器映像</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-prepare-acr">將容器映像上傳至 Azure Container Registry</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-deploy-cluster">在 Azure Container Service 中部署 Kubernetes 叢集</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-deploy-application">在 Kubernetes 中執行容器映像</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-scale">調整應用程式和 Kubernetes 基礎結構</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-app-update">更新在 Kubernetes 中執行的應用程式</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-monitor">透過 OMS 監視 Kubernetes</a>
  - title: 範例
    items:
      - type: list
        style: unordered
        className: spaced noBullet
        items:
          - html: <a href="/azure/container-service/cli-samples">Azure CLI</a>
  - title: 參考
    items:
      - type: list
        style: cards
        className: cardsD
        items:
          - title: 命令列
            html: <p><a href="/cli/azure/acs">Azure CLI</a></p>
          - title: REST
            html: <p><a href="/rest/api/compute/containerservices">REST API</a></p>